name: Upload Artifact
description: Uploads artifact to S3 and returns the URL
inputs:
  aws-account-id:
    required: true
  file-path:
    required: true
  content-type:
    required: false
    default: 'text/html'
  shard:
    required: false
    default: ''

outputs:
  artifact-url:
    description: 'The full URL of the uploaded artifact'
    value: ${{ steps.upload-unix.outputs.artifact-url || steps.upload-windows.outputs.artifact-url }}

runs:
  using: composite
  steps:
    - uses: mapbox/configure-aws-credentials-internal@v5
      with:
        target-account-id: ${{ inputs.aws-account-id }}

    - id: upload-unix
      if: runner.os != 'Windows'
      shell: bash
      env:
        SHARD: ${{ inputs.shard }}
        ARTIFACTS_BASE_URL: hey.mapbox.com/mapbox-gl-js-internal/ci
        FILE_PATH: ${{ inputs.file-path }}
        CONTENT_TYPE: ${{ inputs.content-type }}
      run: bash "$GITHUB_ACTION_PATH/upload.sh"

    - id: upload-windows
      if: runner.os == 'Windows'
      shell: powershell
      env:
        SHARD: ${{ inputs.shard }}
        ARTIFACTS_BASE_URL: hey.mapbox.com/mapbox-gl-js-internal/ci
        FILE_PATH: ${{ inputs.file-path }}
        CONTENT_TYPE: ${{ inputs.content-type }}
      run: |
        $bash = "$env:USERPROFILE\scoop\apps\git\current\bin\bash.exe"
        & $bash "$env:GITHUB_ACTION_PATH/upload.sh"
